### ISSUE TITLE
docker-compose up --build 

### ISSUE THREAD

**Issue by ghost** [Satej/drag-drop-nextjs#1]
backend-1   | exec /app/entrypoint.sh: no such file or directory
db-1        | running bootstrap script ... ok
db-1        | sh: locale: not found
db-1        | 2024-10-15 11:49:17.034 UTC [35] WARNING:  no usable system locales were found
backend-1 exited with code 1

log : drag-drop-nextjs-backend-1
2024-10-15 13:49:16 exec /app/entrypoint.sh: no such file or directory

+ need add to ./backend/Dockerfile or delete from file "M^"
RUN dos2unix /app/entrypoint.sh

**Comment by Satej** [comment]
I do not see this issue at my end. can you please share the operating system and docker and docker-compose versions you are using?
```

~/drag-drop-nextjs$ docker --version
Docker version 26.1.3, build 26.1.3-0ubuntu1
~/drag-drop-nextjs$ docker-compose --version
docker-compose version 1.29.2, build unknown
```

Below is a log of statements at my end:
https://pastebin.com/JnfRqL1J

**Comment by Satej** [comment]
To keep it simple for you to start, I have removed the entrypoint.sh file from the docker-compose yaml file. This file was needed to wait for postgres to be ready to accept new connections the very first time. Please access the change at https://github.com/Satej/drag-drop-nextjs/tree/approach-1 in new branch.

Once cloned:
1. In one terminal run `docker-compose up db`
2. Once you see in the output: `db_1        | 2024-10-15 16:39:08.312 UTC [1] LOG:  database system is ready to accept connections`, run below in another terminal
3. `docker-compose up --build frontend backend`

Hope this helps!

**Comment by ghost** [comment]
drag-drop-nextjs> docker --version
Docker version 27.2.0, build 3ab4256
drag-drop-nextjs> docker-compose --version
Docker Compose version v2.28.1-desktop.1

It is interesting that docker did not see this file (entrypoint.sh), even tried to create a volume. I saw the file with my own eyes, in the right place. But not docker... mysticism...

I saw "^M" at the end of the first two lines - I thought this was the reason. You can't see them under Windows 10, but you can see them inside the container (with the Unix system).

I have been working with docker +/- month, thank you. It was interesting.
